### ISSUE TITLE
Touch events not fully consumed 

### ISSUE THREAD

**Issue by nicktmro** [pavel163/BifacialView#1]
When embedding the `BifacialView` in a `ViewPager`, the sideways pan gesture also gets handled by the parent `ViewPager`. The outcome is that the interaction with the `BifactialView` gets interrupted by the `ViewPager` as it begins to change pages.

Maybe there's a need to call `requestDisallowInterceptTouchEvent` on the parent view in order to consume the gesture in the `BifacialView`?

**Comment by nicktmro** [comment]
[Here's a gist](https://gist.github.com/nicktmro/09fca773385c17f94f7fe792ffacbeed) of how I ended up addressing the issue described above (in case anyone else need it).

**Comment by pavel163** [comment]
@nicktmro Thanks. Use 1.2.0 version. I added touchMode. Use app:touchMode="delimiter".

**Comment by nicktmro** [comment]
Sorry, but upon testing the `app:touchMode="delimiter"` options, things are worse than before.
I looked into the implementation, I wonder if the logic should be in the `ACTION_MOVE` case rather than `ACTION_DOWN`?
